// 04.webFarmework/00.skedo-courses/skedo-example-apps/day11-formdsl/src/Input.tsx
import React, { useEffect, useRef } from "react"

export const Input = (props : {
  defaultValue : any,
  onChange : (value : any) => void
}) => {
  const ref = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if(ref.current!.value !== props.defaultValue) {
      ref.current!.value = props.defaultValue 
    }
  }, [props.defaultValue])
  
  return (
    <input
      ref={ref}
      onChange={(e) => {
        props.onChange && props.onChange(e.target.value)
      }}
    />
  )
}

// 04.webFarmework/00.skedo-courses/vue3-examples/src/components/Input.tsx
import {defineComponent, PropType, ref, watch} from 'vue'
export const Input = defineComponent({
  props: {
    onChange: {
      type: Function as PropType<(v: any) => void>,
      required: false,
    },
    value: {
      type: String,
      required: false,
    },
  },
  setup(props) {
    const input = ref<HTMLInputElement | null>(null)

    watch(
      () => props.value,
      () => {
        const ipt = input.value!
        if(ipt.value !== props.value) {
          ipt.value = props.value || ""
        }
      }
    )
    return () => {
      return (
        <input onInput={e => {
          props.onChange &&
            props.onChange(
              (e.target as HTMLInputElement).value
            )
        }} value={props.value} ref={input} />
      )
    }
  },
})
