// 04.webFarmework/00.skedo-courses/vue3-examples/src/components/drag-drop/component/Draggable.tsx
import { ref, SetupContext, VNode } from "vue"
import {lexicalCache, lexicalScoped} from '@skedo/vue-lexical-cache'
import { DragEvents, DraggableProps, RawDragEvents } from "../types/editor.types"
import { useDragNode } from "../hook/useDragNode"
import DragNode from "../object/DragNode"
import { deepMerge } from "../util/deepMerge"

lexicalScoped('ref')

function assignPropsToVNode(vNode : VNode, props : any) {
	vNode.props = deepMerge(vNode.props, props) 
	return vNode
}

function addPropsToVNode(vNode : VNode, handlers : RawDragEvents, props : DraggableProps, node : DragNode) {

	const vNodeProps : any = {
		...handlers,
		draggable : true
	}

	vNodeProps.style = {
		position : 'absolute',
		top : props.initialPosition[1] + 'px',
		left : props.initialPosition[0] + 'px',
		transform : `translate(${node.diffX}px, ${node.diffY}px)`
	}

	vNode = assignPropsToVNode(vNode, vNodeProps)
	return vNode
}

const Draggable = (props : DraggableProps, ctx : SetupContext) => {
	const [node, handlers] = useDragNode(props, props.initialPosition)
	let vNode : VNode = ctx.slots.default!()[0]
	vNode = addPropsToVNode(vNode, handlers, props, node.value)
	return vNode
}

export default Draggable
// <Draggable><div a={1}>...</div></Draggable>

// 04.webFarmework/00.skedo/packages/skedo-ui/src/components/draggable/Draggable.tsx
import { useDragNode } from "./useDragNode"
import { DragEvents } from "./draggable.types"
import React from "react"
import { mergeDeepLeft } from 'ramda'

type DraggableProps = {
	initialPosition : [string, string],
	children : JSX.Element,
	enabled : boolean,
	style ? : any
} & DragEvents 


const Draggable = (props : DraggableProps) : JSX.Element => {
	const [node, handlers] = useDragNode(props)


	const children = props.children
	const childrenProps = children.props

	const style : any = {
		position : 'absolute',
		top : props.initialPosition[1] ,
		left : props.initialPosition[0],
		...props.style,
	}

	if(props.enabled) {
		style.transform = `translate(${node.diffX}px, ${node.diffY}px)` 
	}

	if(node.dragging) {
		style.position = 'absolute'
	}
	
	const draggableProps : any = {
		draggable : props.enabled,
		dragHandlers : handlers,
		style
	}

	const finalProps = mergeDeepLeft(childrenProps, draggableProps) 
	 return React.cloneElement(children, finalProps)
}

export default Draggable
